import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AppShell, PageTitle, Stat } from "@/components/AppShell";
import { CircuitMap } from "@/components/CircuitMap";
import { SimControls } from "@/components/SimControls";
import { useSim } from "@/lib/sim-store";
import {
  density,
  detectBottlenecks,
  inside,
  queued,
  recommendations,
} from "@/lib/sim";
import { EVENT_SCHEDULE, NODE_MAP, clockLabel, scheduleAt } from "@/lib/venue";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Live Crowd Map — Crowd Flow Optimiser" },
      {
        name: "description",
        content:
          "Real-time simulated crowd density, bottleneck detection and rerouting for a Formula 1 circuit.",
      },
      { property: "og:title", content: "Live Crowd Map — Crowd Flow Optimiser" },
      {
        property: "og:description",
        content: "Simulating and rerouting crowds in real time across an 8-gate motorsport venue.",
      },
    ],
  }),
  component: LivePage,
});

function LivePage() {
  const { state, params, history } = useSim();
  const [selected, setSelected] = useState<string | null>(null);
  const bottlenecks = detectBottlenecks(state, params);
  const recs = recommendations(state, params);
  const critical = bottlenecks.filter((b) => b.severity === "critical").length;
  const node = selected ? NODE_MAP[selected] : null;

  return (
    <AppShell>
      <PageTitle
        title="Live crowd map"
        subtitle="Every figure on this screen is generated by the built-in crowd simulation — feeds from cameras, Wi-Fi and turnstiles are mocked."
      />

      <div className="mb-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
        <Stat label="Inside venue" value={Math.round(inside(state)).toLocaleString()} hint={`of ${params.crowdSize.toLocaleString()} expected`} />
        <Stat label="Queueing at gates" value={Math.round(queued(state)).toLocaleString()} hint="across 8 entry points" tone={queued(state) > 4000 ? "warning" : "default"} />
        <Stat label="Active bottlenecks" value={String(bottlenecks.length)} hint={`${critical} critical`} tone={critical ? "critical" : bottlenecks.length ? "warning" : "ok"} />
        <Stat label="Busiest zone" value={busiest(state)} hint="highest density right now" />
        <Stat label="Event phase" value={scheduleAt(state.t).label} hint={clockLabel(state.t)} />
      </div>

      <div className="mb-4">
        <SimControls />
      </div>

      <div className="grid gap-4 xl:grid-cols-[minmax(0,2.2fr)_minmax(0,1fr)]">
        <div className="space-y-4">
          <CircuitMap state={state} params={params} selected={selected} onSelect={setSelected} />

          <div className="panel p-3 sm:p-4">
            <div className="label-xs mb-3">Occupancy vs gate queues</div>
            <div className="h-48">
              <ResponsiveContainer width="100%" height="100%">
                <AreaChart data={history}>
                  <defs>
                    <linearGradient id="gIn" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="0%" stopColor="var(--color-chart-2)" stopOpacity={0.6} />
                      <stop offset="100%" stopColor="var(--color-chart-2)" stopOpacity={0} />
                    </linearGradient>
                    <linearGradient id="gQ" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="0%" stopColor="var(--color-chart-1)" stopOpacity={0.6} />
                      <stop offset="100%" stopColor="var(--color-chart-1)" stopOpacity={0} />
                    </linearGradient>
                  </defs>
                  <XAxis dataKey="t" tickFormatter={(t) => clockLabel(t)} stroke="var(--color-muted-foreground)" fontSize={11} />
                  <YAxis stroke="var(--color-muted-foreground)" fontSize={11} width={50} />
                  <Tooltip
                    contentStyle={{
                      background: "var(--color-surface)",
                      border: "1px solid var(--color-border)",
                      borderRadius: 8,
                      fontFamily: "var(--font-mono)",
                      fontSize: 12,
                    }}
                    labelFormatter={(t) => clockLabel(Number(t))}
                    formatter={(v: number) => Math.round(v).toLocaleString()}
                  />
                  <Area type="monotone" dataKey="inside" stroke="var(--color-chart-2)" fill="url(#gIn)" />
                  <Area type="monotone" dataKey="queued" stroke="var(--color-chart-1)" fill="url(#gQ)" />
                </AreaChart>
              </ResponsiveContainer>
            </div>
          </div>
        </div>

        <div className="space-y-4">
          {node && (
            <div className="panel p-3 sm:p-4">
              <div className="label-xs">Selected</div>
              <h3 className="mt-1 text-xl">{node.name}</h3>
              <dl className="mt-3 space-y-2 font-mono text-xs">
                <Row k="Type" v={node.kind} />
                <Row k="Sector" v={node.sector} />
                <Row k="Capacity" v={node.capacity.toLocaleString()} />
                {node.kind === "gate" ? (
                  <Row k="Queue" v={`${Math.round(state.queues[node.id] ?? 0).toLocaleString()} people`} />
                ) : (
                  <>
                    <Row k="Occupancy" v={Math.round(state.occupancy[node.id] ?? 0).toLocaleString()} />
                    <Row k="Density" v={`${Math.round(density(state, node.id) * 100)}%`} />
                  </>
                )}
              </dl>
            </div>
          )}

          <div className="panel p-3 sm:p-4">
            <div className="label-xs mb-3">Live bottlenecks</div>
            {bottlenecks.length === 0 && (
              <p className="font-mono text-xs text-muted-foreground">All zones flowing normally.</p>
            )}
            <ul className="space-y-2">
              {bottlenecks.slice(0, 7).map((b) => (
                <li key={b.id} className="rounded-md border border-border bg-surface-2/50 p-3">
                  <div className="flex items-center justify-between gap-2">
                    <span className="font-display text-sm">{b.name}</span>
                    <span
                      className="rounded px-1.5 py-0.5 font-mono text-[10px] uppercase"
                      style={{ background: `var(--color-${b.severity})`, color: "var(--color-background)" }}
                    >
                      {b.severity}
                    </span>
                  </div>
                  <p className="mt-1 font-mono text-[11px] text-muted-foreground">{b.detail}</p>
                </li>
              ))}
            </ul>
          </div>

          <div className="panel p-3 sm:p-4">
            <div className="label-xs mb-3">Optimiser recommendations</div>
            <ul className="space-y-2">
              {recs.length === 0 && (
                <li className="font-mono text-xs text-muted-foreground">No action needed.</li>
              )}
              {recs.slice(0, 4).map((r) => (
                <li key={r.id} className="rounded-md border-l-2 border-primary bg-surface-2/40 p-3">
                  <div className="font-display text-sm">{r.title}</div>
                  <p className="mt-1 text-xs text-muted-foreground">{r.body}</p>
                  <div className="mt-2 font-mono text-[11px] text-accent">{r.impact}</div>
                </li>
              ))}
            </ul>
          </div>

          <div className="panel p-3 sm:p-4">
            <div className="label-xs mb-3">Event schedule</div>
            <ol className="space-y-2">
              {EVENT_SCHEDULE.map((e) => {
                const done = state.t >= e.t;
                const current = scheduleAt(state.t).t === e.t;
                return (
                  <li key={e.t} className="flex items-center gap-3 font-mono text-xs">
                    <span className={`h-2 w-2 rounded-full ${current ? "bg-primary" : done ? "bg-ok" : "bg-muted-foreground"}`} />
                    <span className="w-12 text-muted-foreground">{clockLabel(e.t)}</span>
                    <span className={current ? "text-foreground" : "text-muted-foreground"}>{e.label}</span>
                  </li>
                );
              })}
            </ol>
          </div>
        </div>
      </div>
    </AppShell>
  );
}

function Row({ k, v }: { k: string; v: string }) {
  return (
    <div className="flex justify-between border-b border-border/60 pb-1">
      <dt className="text-muted-foreground uppercase tracking-widest">{k}</dt>
      <dd>{v}</dd>
    </div>
  );
}

function busiest(state: ReturnType<typeof useSim>["state"]) {
  let best = { name: "—", d: -1 };
  for (const [id, v] of Object.entries(state.occupancy)) {
    const node = NODE_MAP[id];
    if (!node || node.kind !== "zone") continue;
    const d = v / node.capacity;
    if (d > best.d) best = { name: node.name, d };
  }
  return best.name;
}
