"""CrowdFlow contracts — the single source of truth for every runtime.

Authored here in Pydantic, exported to JSON Schema, generated into TypeScript for
the dashboard and app. Generated files are committed so drift shows up as a review
diff rather than a debugging session (D1).
"""

from .decisions import (
    Forecast,
    InterventionCandidate,
    RerouteCommand,
    SafetyOutcome,
    SafetyVerdict,
    ScoreBreakdown,
)
from .standards import (
    ASSUMED_FRAGMENT_MAX_DURATION_S,
    ASSUMED_GEOIND_RADIUS_M,
    ASSUMED_HOP_LATENCY_S,
    ASSUMED_MESH_BUFFER_MESSAGES,
    ASSUMED_RADIO_RANGE_CROWD_M,
    ASSUMED_SPRAY_COPY_SCALING,
    ASSUMED_UPLINK_BATTERY_RESERVE,
    ASSUMED_URGENT_BURST_RELAYS,
    ASSUMED_URGENT_RELAYS_PER_MIN,
    BAND_BUILDING_MAX,
    BAND_NOMINAL_MAX,
    CAPACITY_DENSITY,
    DENSITY_BUILDING_MAX,
    DENSITY_NOMINAL_MAX,
    FREE_FLOW_SPEED_MS,
    GEOIND_EPSILON_VENUE,
    GEOIND_PRIVACY_LEVEL,
    JAM_DENSITY_PERSONS_M2,
    LOS_A_MAX,
    LOS_B_MAX,
    LOS_C_MAX,
    LOS_D_MAX,
    LOS_E_MAX,
    MAD_TO_SIGMA,
    MEASURED_NOT_ASSUMED,
    MEASURED_SAMPLE_FLOOR,
    MODIFIED_Z_OUTLIER,
    MESH_TTL_MAX,
    PROPHET_BETA,
    PROPHET_GAMMA,
    PROPHET_P_INIT,
    PROPHET_TIME_UNIT_S,
    LOSBand,
    band_for_density,
    band_for_flow,
    dedupe_retention_s,
    density_for_flow,
    los_grade_for_flow,
    prophet_time_unit_s,
    spray_copies_for,
)
from .state import Confidence, VenueState, ZoneState
from .telemetry import (
    CrowdNode,
    MeshClass,
    MeshMessage,
    MeshMessageType,
    Position,
    TraceFragment,
)
from .venue import (
    Availability,
    CircuitPack,
    CoordinateFrame,
    Crossing,
    CrossingKind,
    Edge,
    EventProfile,
    Provenance,
    SafetyConstraints,
    Session,
    Sourced,
    Zone,
    ZoneKind,
)

__all__ = [
    "ASSUMED_FRAGMENT_MAX_DURATION_S",
    "ASSUMED_GEOIND_RADIUS_M",
    "ASSUMED_HOP_LATENCY_S",
    "ASSUMED_MESH_BUFFER_MESSAGES",
    "ASSUMED_RADIO_RANGE_CROWD_M",
    "ASSUMED_SPRAY_COPY_SCALING",
    "ASSUMED_UPLINK_BATTERY_RESERVE",
    "ASSUMED_URGENT_BURST_RELAYS",
    "ASSUMED_URGENT_RELAYS_PER_MIN",
    "BAND_BUILDING_MAX",
    "BAND_NOMINAL_MAX",
    "CAPACITY_DENSITY",
    "DENSITY_BUILDING_MAX",
    "DENSITY_NOMINAL_MAX",
    "FREE_FLOW_SPEED_MS",
    "GEOIND_EPSILON_VENUE",
    "GEOIND_PRIVACY_LEVEL",
    "JAM_DENSITY_PERSONS_M2",
    "LOS_A_MAX",
    "LOS_B_MAX",
    "LOS_C_MAX",
    "LOS_D_MAX",
    "LOS_E_MAX",
    "MAD_TO_SIGMA",
    "MEASURED_NOT_ASSUMED",
    "MEASURED_SAMPLE_FLOOR",
    "MODIFIED_Z_OUTLIER",
    "MESH_TTL_MAX",
    "PROPHET_BETA",
    "PROPHET_GAMMA",
    "PROPHET_P_INIT",
    "PROPHET_TIME_UNIT_S",
    "Availability",
    "CircuitPack",
    "Confidence",
    "CoordinateFrame",
    "Crossing",
    "CrossingKind",
    "CrowdNode",
    "Edge",
    "EventProfile",
    "Forecast",
    "InterventionCandidate",
    "LOSBand",
    "MeshClass",
    "MeshMessage",
    "MeshMessageType",
    "Position",
    "Provenance",
    "RerouteCommand",
    "SafetyConstraints",
    "SafetyOutcome",
    "SafetyVerdict",
    "ScoreBreakdown",
    "Session",
    "Sourced",
    "TraceFragment",
    "VenueState",
    "Zone",
    "ZoneKind",
    "ZoneState",
    "band_for_density",
    "band_for_flow",
    "dedupe_retention_s",
    "density_for_flow",
    "los_grade_for_flow",
    "prophet_time_unit_s",
    "spray_copies_for",
]

__version__ = "0.1.0"
