import type { CircuitPack, CrowdNode, MeshMessage, TraceFragment } from './types.js';

export class ContractValidationError extends Error {}
export function validateCrowdNode(value: CrowdNode): CrowdNode {
  if (!value.node_id) fail('node_id is required'); if (!Number.isInteger(value.epoch) || value.epoch < 0) fail('epoch must be non-negative');
  if (!(value.speed_ms >= 0)) fail('speed_ms must be non-negative'); if (!(value.heading_deg >= 0 && value.heading_deg < 360)) fail('heading_deg must be in [0,360)'); if (!(value.accuracy_m > 0)) fail('accuracy_m must be positive'); validatePosition(value.position); return value;
}
export function validateTraceFragment(value: TraceFragment): TraceFragment { if (!value.fragment_id) fail('fragment_id is required'); if (value.points.length < 2) fail('trace needs at least two points'); if (!(value.t_end >= value.t_start)) fail('t_end precedes t_start'); if (!(value.epsilon > 0) || !(value.noise_radius_m > 0)) fail('privacy parameters must be positive'); value.points.forEach(validatePosition); return value; }
export function validateMeshMessage(value: MeshMessage): MeshMessage { if (!['state', 'uplink', 'urgent'].includes(value.traffic_class)) fail('traffic_class is required'); if (!Number.isInteger(value.sequence) || value.sequence < 0) fail('sequence must be non-negative'); if (!Number.isInteger(value.ttl) || value.ttl < 0) fail('ttl must be non-negative'); return value; }
export function validateCircuitPack(pack: CircuitPack): CircuitPack { const problems = circuitIntegrityProblems(pack); if (problems.length) fail(problems.join('; ')); return pack; }
export function circuitIntegrityProblems(pack: CircuitPack): string[] { const zones = pack.zones ?? {}; const edges = pack.edges ?? {}; const problems: string[] = []; const degree = new Map(Object.keys(zones).map((id) => [id, 0])); for (const edge of Object.values(edges)) { if (!(edge.length_m > 0) || !(edge.width_m.value > 0)) problems.push(`edge ${edge.id}: dimensions must be positive`); if (!(edge.source in zones)) problems.push(`edge ${edge.id}: unknown source`); else degree.set(edge.source, degree.get(edge.source)! + 1); if (!(edge.destination in zones)) problems.push(`edge ${edge.id}: unknown destination`); else degree.set(edge.destination, degree.get(edge.destination)! + 1); } for (const [id, count] of degree) if (count === 0) problems.push(`zone ${id}: orphaned`); for (const crossing of Object.values(pack.crossings ?? {})) if (!(crossing.edge_id in edges)) problems.push(`crossing ${crossing.id}: unknown edge`); for (const exit of pack.constraints?.emergency_exits ?? []) if (!(exit in zones)) problems.push(`emergency exit ${exit}: unknown zone`); return problems; }
function validatePosition(position: { x: number; y: number }): void { if (!Number.isFinite(position.x) || !Number.isFinite(position.y)) fail('position must be finite'); }
function fail(message: string): never { throw new ContractValidationError(message); }
