import type { CircuitPack, Edge, Position, Provenance, Sourced, Zone, ZoneKind } from '@crowdflow/contracts';
import { Frame, pointToSegmentDistance, segmentsIntersect, widthFor, type OsmNode, type OsmWay } from './venue.js';

export const ASSUMED_OSM_SNAP_M = 8;
export const ASSUMED_GATE_TOLERANCE_M = 12;
export const ASSUMED_MIN_EDGE_M = 3;
export const ASSUMED_SEMANTIC_ATTACH_MAX_M = 120;
export const ASSUMED_ACCESS_STUB_WIDTH_M = 4;
export interface BuildStats { ways_in: number; ways_clipped: number; raw_edges: number; barrier_removed: number; gate_preserved: number; edges_out: number; zones_out: number; simplified_away: number; assumed_widths: number; unattached: number }

class Snapper {
  readonly points: Position[] = []; private cells = new Map<string, number[]>();
  constructor(readonly tolerance = ASSUMED_OSM_SNAP_M) {}
  snap(point: Position): number { const [cx, cy] = this.cell(point); for (let dx = -1; dx <= 1; dx += 1) for (let dy = -1; dy <= 1; dy += 1) for (const index of this.cells.get(`${cx + dx}:${cy + dy}`) ?? []) if (distance(point, this.points[index]!) <= this.tolerance) return index; const index = this.points.length; this.points.push(point); const key = `${cx}:${cy}`; const values = this.cells.get(key) ?? []; values.push(index); this.cells.set(key, values); return index; }
  private cell(point: Position): [number, number] { return [Math.floor(point.x / this.tolerance), Math.floor(point.y / this.tolerance)]; }
}

export function buildPack(input: { circuit_id: string; name: string; geometry_source: string; track_length_m: number; altitude_m: number; track_latlon: Array<[number, number]>; ways: OsmWay[]; nodes: OsmNode[]; venue_buffer_m?: number }): { pack: CircuitPack; stats: BuildStats; track: Position[] } {
  if (input.track_latlon.length < 2) throw new Error('track geometry needs at least two points'); const stats: BuildStats = { ways_in: input.ways.length, ways_clipped: 0, raw_edges: 0, barrier_removed: 0, gate_preserved: 0, edges_out: 0, zones_out: 0, simplified_away: 0, assumed_widths: 0, unattached: 0 }; const originLat = Math.min(...input.track_latlon.map(([lat]) => lat)); const originLon = Math.min(...input.track_latlon.map(([, lon]) => lon)); const frame = new Frame(originLat, originLon); const project = ([lat, lon]: [number, number]): Position => { const [x, y] = frame.toXY(lat, lon); return { x, y }; }; const track = input.track_latlon.map(project); const buffer = input.venue_buffer_m ?? 900;
  const projected = input.ways.map((way) => ({ way, points: way.coords.map(project) })).filter(({ points }) => { const keep = nearTrack(points, track, buffer); if (!keep) stats.ways_clipped += 1; return keep; }); const gates = input.nodes.filter((node) => node.kind === 'gate').map((node) => project(node.coord)); const barriers = projected.filter(({ way }) => way.kind === 'barrier').flatMap(({ points }) => points.slice(1).map((point, index) => [points[index]!, point] as const)); const snapper = new Snapper(); const raw: Array<{ source: number; destination: number; length: number; way: OsmWay }> = [];
  for (const { way, points } of projected) { if (way.kind !== 'walkable') continue; const ids = points.map((point) => snapper.snap(point)); for (let index = 0; index < points.length - 1; index += 1) { const a = points[index]!; const b = points[index + 1]!; const source = ids[index]!; const destination = ids[index + 1]!; const length = distance(a, b); if (source === destination || length < ASSUMED_MIN_EDGE_M) continue; stats.raw_edges += 1; if (barriers.some(([c, d]) => segmentsIntersect(a, b, c, d))) { const middle = { x: (a.x + b.x) / 2, y: (a.y + b.y) / 2 }; if (gates.some((gate) => distance(middle, gate) <= ASSUMED_GATE_TOLERANCE_M)) stats.gate_preserved += 1; else { stats.barrier_removed += 1; continue; } } raw.push({ source, destination, length, way }); } }
  const used = new Set(raw.flatMap((edge) => [edge.source, edge.destination])); const zones: Record<string, Zone> = {}; for (const index of [...used].sort((a, b) => a - b)) zones[`n${index}`] = { id: `n${index}`, kind: 'concourse', position: roundPosition(snapper.points[index]!) }; const edges: Record<string, Edge> = {}; raw.forEach((candidate, index) => { const width = widthFor(candidate.way.tags); edges[`e${index}`] = { id: `e${index}`, source: `n${candidate.source}`, destination: `n${candidate.destination}`, length_m: round(candidate.length), width_m: width, bidirectional: true }; });
  const attach = (position: Position, id: string, kind: ZoneKind, name?: string, osmId?: string) => { if (!used.size) return; const nearest = [...used].sort((a, b) => distance(position, snapper.points[a]!) - distance(position, snapper.points[b]!) || a - b)[0]!; const gap = distance(position, snapper.points[nearest]!); if (gap > ASSUMED_SEMANTIC_ATTACH_MAX_M) { stats.unattached += 1; return; } zones[id] = { id, kind, position: roundPosition(position), ...(name ? { name } : {}), ...(osmId ? { osm_id: osmId } : {}) }; edges[`a${id}`] = { id: `a${id}`, source: id, destination: `n${nearest}`, length_m: Math.max(ASSUMED_MIN_EDGE_M, round(gap)), width_m: { value: ASSUMED_ACCESS_STUB_WIDTH_M, provenance: 'assumed', note: 'access stub to nearest path node' }, bidirectional: true }; };
  for (const { way, points } of projected) if (way.kind === 'grandstand' || way.kind === 'parking') attach(centroid(points), `${way.kind === 'grandstand' ? 'stand' : 'park'}_${way.osm_id}`, way.kind === 'grandstand' ? 'viewing' : 'parking', way.name ?? (way.kind === 'grandstand' ? 'Grandstand' : 'Car park'), String(way.osm_id)); for (const node of input.nodes) if (node.kind === 'gate') { const position = project(node.coord); if (nearTrack([position], track, buffer)) attach(position, `gate_${node.osm_id}`, 'gate', node.name, String(node.osm_id)); }
  const simplified = simplifyGraph(zones, edges, new Set(Object.values(zones).filter((zone) => ['gate', 'viewing', 'parking', 'exit'].includes(zone.kind)).map((zone) => zone.id))); stats.simplified_away = simplified.collapsed; stats.edges_out = Object.keys(simplified.edges).length; stats.zones_out = Object.keys(simplified.zones).length; stats.assumed_widths = Object.values(simplified.edges).filter((edge) => edge.width_m.provenance === 'assumed').length; const positions = Object.values(simplified.zones).map((zone) => zone.position); const tx = track.map((point) => point.x); const ty = track.map((point) => point.y); const xs = positions.map((point) => point.x); const ys = positions.map((point) => point.y);
  return { pack: { id: input.circuit_id, name: input.name, geometry_source: input.geometry_source, track_length_m: input.track_length_m, altitude_m: input.altitude_m, frame: { origin_lat: originLat, origin_lon: originLon, track_bounds_m: [round(Math.max(...tx) - Math.min(...tx), 1), round(Math.max(...ty) - Math.min(...ty), 1)], venue_bounds_m: xs.length ? [round(Math.min(...xs), 1), round(Math.min(...ys), 1), round(Math.max(...xs), 1), round(Math.max(...ys), 1)] : [0, 0, 0, 0] }, zones: simplified.zones, edges: simplified.edges, crossings: {}, constraints: {} }, stats, track };
}

export function simplifyGraph(sourceZones: Record<string, Zone>, sourceEdges: Record<string, Edge>, protectedIds = new Set<string>()): { zones: Record<string, Zone>; edges: Record<string, Edge>; collapsed: number } { const zones = { ...sourceZones }; const edges = { ...sourceEdges }; let collapsed = 0; for (const id of Object.keys(zones)) { if (protectedIds.has(id)) continue; const incident = Object.values(edges).filter((edge) => edge.source === id || edge.destination === id); if (incident.length !== 2) continue; const [first, second] = incident as [Edge, Edge]; const a = first.source === id ? first.destination : first.source; const b = second.source === id ? second.destination : second.source; if (a === b || a === id || b === id) continue; const length = first.length_m + second.length_m; const provenance: Provenance = first.width_m.provenance === 'assumed' || second.width_m.provenance === 'assumed' ? 'assumed' : first.width_m.provenance; const width: Sourced = { value: round((first.width_m.value * first.length_m + second.width_m.value * second.length_m) / length), provenance, note: 'length-weighted mean of merged segments' }; delete edges[first.id]; delete edges[second.id]; const edgeId = `m${first.id}_${second.id}`; edges[edgeId] = { id: edgeId, source: a, destination: b, length_m: round(length), width_m: width, gradient: ((first.gradient ?? 0) + (second.gradient ?? 0)) / 2, bidirectional: (first.bidirectional ?? true) && (second.bidirectional ?? true) }; delete zones[id]; collapsed += 1; } const live = new Set(Object.values(edges).flatMap((edge) => [edge.source, edge.destination])); return { zones: Object.fromEntries(Object.entries(zones).filter(([id]) => live.has(id))), edges, collapsed }; }
function nearTrack(points: Position[], track: Position[], buffer: number): boolean { return points.some((point) => track.slice(1).some((end, index) => pointToSegmentDistance(point, track[index]!, end) <= buffer)); }
function centroid(points: Position[]): Position { return { x: points.reduce((sum, point) => sum + point.x, 0) / points.length, y: points.reduce((sum, point) => sum + point.y, 0) / points.length }; }
function distance(a: Position, b: Position): number { return Math.hypot(a.x - b.x, a.y - b.y); }
function round(value: number, digits = 2): number { return Number(value.toFixed(digits)); }
function roundPosition(point: Position): Position { return { x: round(point.x), y: round(point.y) }; }
