import type { CircuitPack, VenueState } from '@crowdflow/contracts';
import { MAD_TO_SIGMA, MODIFIED_Z_OUTLIER } from '@crowdflow/contracts';

export const MIN_BASELINE_POINTS = 8;
export const MIN_PEERS = 3;
export const SESSION_WINDOW = 3;
export type InsightKind = 'self_baseline' | 'peer_gap';
export interface Insight { id: string; kind: InsightKind; metric: string; subject: string; subject_name: string; peer?: string; peer_name?: string; observed: number; baseline: number; deviation: number; relative_change: number; samples: number; sessions: string[]; headline: string; narration?: string }
export function modifiedZ(value: number, sample: number[], minimum = MIN_BASELINE_POINTS): number | null { if (sample.length < minimum) return null; const centre = median(sample); const mad = median(sample.map((item) => Math.abs(item - centre))); return mad <= 0 ? null : (value - centre) / (MAD_TO_SIGMA * mad); }

export class InsightEngine {
  private series = new Map<string, number[]>(); private sessions: string[] = [];
  constructor(readonly pack: CircuitPack, readonly history = 240, readonly sessionWindow = SESSION_WINDOW) {}
  observe(state: VenueState): void { const session = state.session_id ?? 'unassigned'; if (!this.sessions.includes(session)) this.sessions.push(session); for (const [id, zone] of Object.entries(state.zones ?? {})) for (const metric of ['density_persons_m2', 'outflow_per_min', 'mean_speed_ms'] as const) { const key = `${id}:${session}:${metric}`; const values = this.series.get(key) ?? []; values.push(zone[metric]); this.series.set(key, values.slice(-this.history)); } }
  insights(limit?: number): Insight[] { const found = [...this.peerGaps(), ...this.selfBaselines()].sort((a, b) => Math.abs(b.deviation) - Math.abs(a.deviation) || a.id.localeCompare(b.id)); return limit == null ? found : found.slice(0, limit); }
  private selfBaselines(): Insight[] { const out: Insight[] = []; const session = this.sessions.at(-1) ?? 'unassigned'; for (const [key, values] of this.series) { const [subject, seriesSession, metric] = key.split(':') as [string, string, string]; if (seriesSession !== session || values.length <= MIN_BASELINE_POINTS) continue; const observed = values.at(-1)!; const sample = values.slice(0, -1); const score = modifiedZ(observed, sample); if (score == null || Math.abs(score) < MODIFIED_Z_OUTLIER) continue; const baseline = median(sample); const name = this.name(subject); out.push({ id: `self-${subject}-${metric}`, kind: 'self_baseline', metric, subject, subject_name: name, observed: round(observed, 3), baseline: round(baseline, 3), deviation: round(score), relative_change: round(relative(observed, baseline), 4), samples: sample.length, sessions: [session], headline: `${name} ${metric} is ${observed.toFixed(2)}, ${Math.abs(score).toFixed(1)} deviations ${observed > baseline ? 'above' : 'below'} its own baseline of ${baseline.toFixed(2)}` }); } return out; }
  private peerGaps(): Insight[] { const recent = this.sessions.slice(-this.sessionWindow); const gates = Object.values(this.pack.zones ?? {}).filter((zone) => zone.kind === 'gate').map((zone) => zone.id); const out: Insight[] = []; for (const metric of ['density_persons_m2', 'outflow_per_min', 'mean_speed_ms']) { const values = new Map<string, number>(); const counts = new Map<string, number>(); for (const gate of gates) { const perSession = recent.map((session) => this.series.get(`${gate}:${session}:${metric}`) ?? []).filter((sample) => sample.length >= MIN_BASELINE_POINTS); if (!perSession.length) continue; values.set(gate, median(perSession.map(median))); counts.set(gate, perSession.reduce((sum, sample) => sum + sample.length, 0)); } if (values.size < MIN_PEERS + 1) continue; for (const [gate, observed] of values) { const peers = [...values.entries()].filter(([id]) => id !== gate); const score = modifiedZ(observed, peers.map(([, value]) => value).concat(observed), MIN_PEERS + 1); if (score == null || Math.abs(score) < MODIFIED_Z_OUTLIER) continue; const slowerIsLower = metric === 'outflow_per_min' || metric === 'mean_speed_ms'; peers.sort((a, b) => (slowerIsLower ? b[1] - a[1] : a[1] - b[1]) || a[0].localeCompare(b[0])); const [peer, baseline] = peers[0]!; const change = relative(observed, baseline); out.push({ id: `peer-${gate}-${metric}`, kind: 'peer_gap', metric, subject: gate, subject_name: this.name(gate), peer, peer_name: this.name(peer), observed: round(observed, 3), baseline: round(baseline, 3), deviation: round(score), relative_change: round(change, 4), samples: counts.get(gate) ?? 0, sessions: recent, headline: `${this.name(gate)} ${metric} is ${Math.abs(change * 100).toFixed(0)}% ${change < 0 ? 'lower' : 'higher'} than ${this.name(peer)} across the last ${recent.length} session${recent.length === 1 ? '' : 's'}` }); } } return out; }
  private name(id: string): string { return this.pack.zones?.[id]?.name ?? id; }
}
function relative(observed: number, baseline: number): number { return baseline ? (observed - baseline) / Math.abs(baseline) : 0; }
function median(values: number[]): number { const sorted = values.slice().sort((a, b) => a - b); const middle = Math.trunc(sorted.length / 2); return sorted.length % 2 ? sorted[middle]! : (sorted[middle - 1]! + sorted[middle]!) / 2; }
function round(value: number, digits = 2): number { return Number(value.toFixed(digits)); }
