import type { MeshClass, Position } from '@crowdflow/contracts';
import { ASSUMED_RADIO_RANGE_CROWD_M, FREE_FLOW_SPEED_MS, MESH_TTL_MAX, sprayCopiesFor } from '@crowdflow/contracts';
import { Random } from '../random.js';
import { electUplinks, meshCoverage, radioNeighbours } from './uplink.js';

export interface MeshSimConfig { seed: number; node_count: number; span_m: number; radio_range_m: number; tick_s: number; walk_speed_ms: number; data_plan_fraction: number; state_every_ticks: number; uplink_every_ticks: number; urgent_every_ticks: number; ttl: number }
export const DEFAULT_MESH_SIM_CONFIG: MeshSimConfig = { seed: 7, node_count: 150, span_m: 400, radio_range_m: ASSUMED_RADIO_RANGE_CROWD_M, tick_s: 5, walk_speed_ms: FREE_FLOW_SPEED_MS, data_plan_fraction: 0.05, state_every_ticks: 1, uplink_every_ticks: 1, urgent_every_ticks: 20, ttl: MESH_TTL_MAX };
export class PolicyMetrics { created = 0; delivered = 0; transmissions = 0; hops_total = 0; latency_total_s = 0; constructor(readonly traffic_class: MeshClass, readonly policy: string) {} get delivery_ratio(): number { return this.created ? this.delivered / this.created : 0; } get mean_hops(): number { return this.delivered ? this.hops_total / this.delivered : 0; } get copies_per_message(): number { return this.created ? this.transmissions / this.created : 0; } get mean_latency_s(): number { return this.delivered ? this.latency_total_s / this.delivered : 0; } row(): [string, string, number, number, number, number] { return [this.traffic_class, this.policy, round(this.delivery_ratio, 3), round(this.mean_hops), round(this.copies_per_message), round(this.mean_latency_s, 1)]; } }
export class MeshRunMetrics { ticks = 0; mean_uplinks = 0; mean_online_nodes = 0; mean_coverage = 0; readonly by_class: Record<MeshClass, PolicyMetrics> = { state: new PolicyMetrics('state', 'spray-and-wait'), uplink: new PolicyMetrics('uplink', 'spray-and-wait'), urgent: new PolicyMetrics('urgent', 'rate-limited-epidemic') }; rows() { return (['state', 'uplink', 'urgent'] as const).map((kind) => this.by_class[kind].row()); } get epidemic_cost_ratio(): number { return this.by_class.state.copies_per_message ? this.by_class.urgent.copies_per_message / this.by_class.state.copies_per_message : 0; } }
interface Walker { id: string; position: Position; target: Position; online: boolean; throughput: number; battery: number }
interface Packet { key: string; traffic: MeshClass; created: number; holders: Set<string>; delivered: boolean; hops: Map<string, number>; copies: Map<string, number>; forwarded: Set<string> }

/** A seeded, bounded protocol comparison over one shared moving topology. It is
 * deliberately transport-free: handset radios remain behind the Kotlin seam. */
export class MeshSimulator {
  readonly config: MeshSimConfig; readonly rng: Random; readonly walkers: Walker[] = []; readonly metrics = new MeshRunMetrics(); now = 0; private sequence = 0; private packets: Packet[] = []; private uplinkTotal = 0; private onlineTotal = 0; private coverageTotal = 0;
  constructor(config: Partial<MeshSimConfig> = {}) { this.config = { ...DEFAULT_MESH_SIM_CONFIG, ...config }; this.rng = new Random(this.config.seed); for (let index = 0; index < this.config.node_count; index += 1) { const position = this.point(); const online = this.rng.random() < this.config.data_plan_fraction; this.walkers.push({ id: `n${index.toString().padStart(4, '0')}`, position, target: this.point(), online, throughput: online ? this.rng.uniform(50, 2000) : 0, battery: 0.5 }); } }
  run(ticks = 200): MeshRunMetrics { for (let tick = 0; tick < ticks; tick += 1) { if (tick % this.config.state_every_ticks === 0) this.inject('state'); if (tick % this.config.uplink_every_ticks === 0) this.inject('uplink'); if (tick % this.config.urgent_every_ticks === 0) this.inject('urgent'); this.step(); } this.metrics.ticks = ticks; if (ticks) { this.metrics.mean_uplinks = this.uplinkTotal / ticks; this.metrics.mean_online_nodes = this.onlineTotal / ticks; this.metrics.mean_coverage = this.coverageTotal / ticks; } return this.metrics; }
  private inject(traffic: MeshClass): void { const source = this.walkers[Math.trunc(this.rng.random() * this.walkers.length)]!; const copies = traffic === 'urgent' ? 1 : sprayCopiesFor(this.walkers.length); this.packets.push({ key: `${source.id}:${this.sequence++}`, traffic, created: this.now, holders: new Set([source.id]), delivered: source.online, hops: new Map([[source.id, 0]]), copies: new Map([[source.id, copies]]), forwarded: new Set() }); const metrics = this.metrics.by_class[traffic]; metrics.created += 1; if (source.online) { metrics.delivered += 1; } }
  private step(): void { this.now += this.config.tick_s; this.move(); const adjacency = radioNeighbours(this.walkers, this.config.radio_range_m); const candidates = this.walkers.map((node) => ({ node_id: node.id, online: node.online, battery: node.battery, throughput_kbps: node.throughput, peer_degree: adjacency[node.id]?.size ?? 0 })); const election = electUplinks(candidates, adjacency); this.uplinkTotal += election.uplinks.length; this.onlineTotal += this.walkers.filter((node) => node.online).length; this.coverageTotal += meshCoverage(adjacency, election.uplinks, {}, this.config.ttl).node_fraction; const byId = new Map(this.walkers.map((node) => [node.id, node]));
    for (const packet of this.packets) { if (packet.delivered) continue; const holders = [...packet.holders].sort(); for (const sender of holders) { if (packet.delivered) break; for (const receiver of [...(adjacency[sender] ?? [])].sort()) { const link = `${packet.key}:${sender}:${receiver}`; if (packet.forwarded.has(link) || packet.holders.has(receiver)) continue; const hops = (packet.hops.get(sender) ?? 0) + 1; if (hops > this.config.ttl) continue; const peer = byId.get(receiver)!; let send = false; let transfer = 1; if (packet.traffic === 'urgent') send = this.metrics.by_class.urgent.transmissions < this.metrics.by_class.urgent.created * 15; else { const copies = packet.copies.get(sender) ?? 1; if (copies > 1) { send = true; transfer = Math.max(1, Math.trunc(copies / 2)); } else send = peer.online; } if (!send) continue; packet.forwarded.add(link); packet.holders.add(receiver); packet.hops.set(receiver, hops); packet.copies.set(receiver, transfer); if (packet.traffic !== 'urgent') packet.copies.set(sender, Math.max(1, (packet.copies.get(sender) ?? 1) - transfer)); const metrics = this.metrics.by_class[packet.traffic]; metrics.transmissions += 1; if (peer.online) { packet.delivered = true; metrics.delivered += 1; metrics.hops_total += hops; metrics.latency_total_s += this.now - packet.created; break; } } } }
  }
  private move(): void { const step = this.config.walk_speed_ms * this.config.tick_s; for (const walker of this.walkers) { const dx = walker.target.x - walker.position.x; const dy = walker.target.y - walker.position.y; const distance = Math.hypot(dx, dy); if (distance <= step) { walker.position = walker.target; walker.target = this.point(); } else walker.position = { x: walker.position.x + step * dx / distance, y: walker.position.y + step * dy / distance }; } }
  private point(): Position { return { x: this.rng.uniform(0, this.config.span_m), y: this.rng.uniform(0, this.config.span_m) }; }
}
export function comparePolicies(config: Partial<MeshSimConfig> = {}, ticks = 200): MeshRunMetrics { return new MeshSimulator(config).run(ticks); }
function round(value: number, digits = 2): number { return Number(value.toFixed(digits)); }
