/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as CircuitsRouteImport } from './routes/circuits'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as EvacuationRouteImport } from './routes/evacuation'
import { Route as FeedsRouteImport } from './routes/feeds'
import { Route as LayoutRouteImport } from './routes/layout'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RoutingRouteImport } from './routes/routing'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as SpectatorRouteImport } from './routes/spectator'
import { Route as ZonesRouteImport } from './routes/zones'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const CircuitsRoute = CircuitsRouteImport.update({
  id: '/circuits',
  path: '/circuits',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const EvacuationRoute = EvacuationRouteImport.update({
  id: '/evacuation',
  path: '/evacuation',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedsRoute = FeedsRouteImport.update({
  id: '/feeds',
  path: '/feeds',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/layout',
  path: '/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutingRoute = RoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const SpectatorRoute = SpectatorRouteImport.update({
  id: '/spectator',
  path: '/spectator',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesRoute = ZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/circuits': typeof CircuitsRoute
  '/copilot': typeof CopilotRoute
  '/evacuation': typeof EvacuationRoute
  '/feeds': typeof FeedsRoute
  '/layout': typeof LayoutRoute
  '/reports': typeof ReportsRoute
  '/routing': typeof RoutingRoute
  '/simulation': typeof SimulationRoute
  '/spectator': typeof SpectatorRoute
  '/zones': typeof ZonesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/circuits': typeof CircuitsRoute
  '/copilot': typeof CopilotRoute
  '/evacuation': typeof EvacuationRoute
  '/feeds': typeof FeedsRoute
  '/layout': typeof LayoutRoute
  '/reports': typeof ReportsRoute
  '/routing': typeof RoutingRoute
  '/simulation': typeof SimulationRoute
  '/spectator': typeof SpectatorRoute
  '/zones': typeof ZonesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/circuits': typeof CircuitsRoute
  '/copilot': typeof CopilotRoute
  '/evacuation': typeof EvacuationRoute
  '/feeds': typeof FeedsRoute
  '/layout': typeof LayoutRoute
  '/reports': typeof ReportsRoute
  '/routing': typeof RoutingRoute
  '/simulation': typeof SimulationRoute
  '/spectator': typeof SpectatorRoute
  '/zones': typeof ZonesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/circuits'
    | '/copilot'
    | '/evacuation'
    | '/feeds'
    | '/layout'
    | '/reports'
    | '/routing'
    | '/simulation'
    | '/spectator'
    | '/zones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/circuits'
    | '/copilot'
    | '/evacuation'
    | '/feeds'
    | '/layout'
    | '/reports'
    | '/routing'
    | '/simulation'
    | '/spectator'
    | '/zones'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/circuits'
    | '/copilot'
    | '/evacuation'
    | '/feeds'
    | '/layout'
    | '/reports'
    | '/routing'
    | '/simulation'
    | '/spectator'
    | '/zones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  CircuitsRoute: typeof CircuitsRoute
  CopilotRoute: typeof CopilotRoute
  EvacuationRoute: typeof EvacuationRoute
  FeedsRoute: typeof FeedsRoute
  LayoutRoute: typeof LayoutRoute
  ReportsRoute: typeof ReportsRoute
  RoutingRoute: typeof RoutingRoute
  SimulationRoute: typeof SimulationRoute
  SpectatorRoute: typeof SpectatorRoute
  ZonesRoute: typeof ZonesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circuits': {
      id: '/circuits'
      path: '/circuits'
      fullPath: '/circuits'
      preLoaderRoute: typeof CircuitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evacuation': {
      id: '/evacuation'
      path: '/evacuation'
      fullPath: '/evacuation'
      preLoaderRoute: typeof EvacuationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeds': {
      id: '/feeds'
      path: '/feeds'
      fullPath: '/feeds'
      preLoaderRoute: typeof FeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layout': {
      id: '/layout'
      path: '/layout'
      fullPath: '/layout'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routing': {
      id: '/routing'
      path: '/routing'
      fullPath: '/routing'
      preLoaderRoute: typeof RoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spectator': {
      id: '/spectator'
      path: '/spectator'
      fullPath: '/spectator'
      preLoaderRoute: typeof SpectatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones': {
      id: '/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof ZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  CircuitsRoute: CircuitsRoute,
  CopilotRoute: CopilotRoute,
  EvacuationRoute: EvacuationRoute,
  FeedsRoute: FeedsRoute,
  LayoutRoute: LayoutRoute,
  ReportsRoute: ReportsRoute,
  RoutingRoute: RoutingRoute,
  SimulationRoute: SimulationRoute,
  SpectatorRoute: SpectatorRoute,
  ZonesRoute: ZonesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
